name: 'Slack notify release action'
description: 'A simple GitHub action to post a Slack message when a new version is released.'
author: 'italia'

inputs:
  slack_token:
    description: 'Slack token'
    required: true
  channel_id:
    description: 'Channel ID'
    required: true
  project_name:
    description: 'Project name to display'
    required: true
  repo_name:
    description: 'Repo name (e.g. "italia/design-comuni-wordpress-theme")'
    required: true

outputs:
  status:
    description: 'The status of message sent'
  license:
    description: 'The license used in the repository'

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'activity'
  color: 'white'
